config/routes.rb
Rails.application.routes.draw do

  root 'page#home'

  get 'page/mailing'
  get 'page/legal'

  resources :charges

  devise_for :users

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'

  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  def add
    puts "harambe add to cart"
    puts params[:sizing]
    @thissize = Rails.cache.write("thissize", params[:sizing])
    id = params[:id]
        if session[:cart] then
            cart = session[:cart]
        else
            session[:cart] = {}
            cart = session[:cart]
        end
        if cart[id] then
            cart[id] += 1
        else
            cart[id] = 1
        end
        redirect_to :action => :index
    end

  def clearCart
    session[:cart] = nil
    redirect_to products_path
  end

  def index
    @thissize = Rails.cache.read("thissize")
    if session[:cart] then
        @cart = session[:cart]
    else
        @cart = {}
    end
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

    def new
    end

    def create
      # Amount in cents
      @amount = params[:prix]

      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'Rails Stripe customer',
        :currency    => 'usd'
      )

      rescue Stripe::CardError => e
        flash[:error] = e.message
        puts "harambe pay"
        redirect_to new_charge_path
      
    end

    def success
      redirect_to cart_clear_path
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def mailing
  end

  def legal
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price, :category, :subcategory)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/index.html.erb
<div style="padding-top: 10%" />

<h1 id="cart_title">Cart</h1>

<div id="cart_meat">


  <% if @cart.empty? %>
      <h2> 
        <br /> <br />
        <br /> <br />
        nothing here /
        an empty cart rattles loudly </h2>
        <div style="padding-top: 60%" />
  <% else %>

    <% total = 0 %>

    <table id="cart_list">
      <% @cart.each do | id, quantity | %>
          <% product = Product.find_by_id(id) %>
          <tr>
              <td>
                <%= link_to product.title, product %>
              </td>
              <td class="deux">
                <h3> <%= product.price %> </h3>
              </td>
              <td>
                <span class="quantity">(<%= quantity %>)</span>
              </td>
          </tr>

          <% total += quantity * product.price %>

      <% end %>
    </table>

    <div id="cart_pay">

      <%= form_tag('/charges', method: :post) do %>
        <article>
          <% if flash[:error].present? %>
            <div id="error_explanation">
              <p><%= flash[:error] %></p>
            </div>
          <% end %>
          <label class="total">
            <h4> <span id="special"> TOTAL </span> <%= total %> </h4>
          </label>
        </article>
        <input type="hidden" name="prix" value="<%= total * 100 %>">

        <span style="filter: invert(0%) grayscale(77%) opacity(66%);">
          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="BLACKWATER ATELIER"
                data-amount="<%= total * 100 %>"
                data-locale="auto">
          </script>
        </span>
      <% end %>
    </div>

    <div id="clearcart">
      <h8> your size:</h8><h9> <%= @thissize %> </h9> <br />
      <a href="<%= cart_clear_path %>"> clear cart </a>
    </div>
  <% end %>

</div>
<div style="padding-top: 10%" />

app/views/charges/create.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>BLACKWATER</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%-# the answers you seek will not be found -%>
</head>
<body>

  

<nav id="nav">
    <a href="/">
      <div id="logo">
          <img src='https://s3.amazonaws.com/bwla/new%2Blogo.png' />
          <h1>BLACKWATER ATELIER</h1>
          <h2>los angeles</h2>
        </a>
      </div>
    </a>
    <div id="shop_nav">
      <%= link_to "Shop", products_path %>
    </div>

    <div id="cart_nav">
      <%= link_to "Cart", cart_path %>
    </div>
</nav>


<div class="wrapper">
  <div id="alerts">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

<div id="main_wrap">
    

    <% session[:cart] = nil %>

    <div id="thanks_container">
        <div style="padding: 5% 0"></div>
        <h2 id="thanks">THANK YOU FOR YOUR PURCHASE</h2>
    </div>



</div>



<div class="push"></div>
</div>

<div style="padding-top: 5%" />

<div class="footer">
      <%= link_to "Press", new_user_session_path %>
      <%= link_to "Mailing List", page_mailing_path %>
      <%= link_to "Legal", page_legal_path %>
      <% if user_signed_in? %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% else %>
          <%= link_to "Sign In", new_user_session_path %>
      <% end %>

      <h3>CONCIEVED IN LA / TRANSCENDED IN PARIS / CONSERVE BLACKWATER</h3>

</div>

</body>
</html>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/charges/success.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>BLACKWATER</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%-# the answers you seek will not be found -%>
</head>
<body>

  

<nav id="nav">
    <a href="/">
      <div id="logo">
          <img src='https://s3.amazonaws.com/bwla/new%2Blogo.png' />
          <h1>BLACKWATER ATELIER</h1>
          <h2>los angeles</h2>
        </a>
      </div>
    </a>
    <div id="shop_nav">
      <%= link_to "Shop", products_path %>
    </div>

    <div id="cart_nav">
      <%= link_to "Cart", cart_path %>
    </div>
</nav>


<div class="wrapper">
  <div id="alerts">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

<div id="main_wrap">
    <%= yield %>
</div>



<div class="push"></div>
</div>

<div style="padding-top: 5%" />

<div class="footer">
      <%= link_to "Press", new_user_session_path %>
      <%= link_to "Mailing List", page_mailing_path %>
      <%= link_to "Legal", page_legal_path %>
      <% if user_signed_in? %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% else %>
          <%= link_to "Sign In", new_user_session_path %>
      <% end %>

      <h3>CONCIEVED IN LA / TRANSCENDED IN PARIS / CONSERVE BLACKWATER</h3>

</div>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/page/about.html.erb
<div style="padding-top: 10%" />

app/views/page/contact.html.erb
<div style="padding-top: 10%" />

app/views/page/faqs.html.erb
<div style="padding-top: 10%" />

app/views/page/home.html.erb
<!-- svg is defined here because of a Safari bug with <use> -->
  <svg>
    <defs>
      <g id="p">
        <path opacity=".2" d="M0 2h252s-3.3 40.7-2.7 128.3C249 216 252 272 252 272s-88-2-124.3-2C91.3 270 0 272 0 272V0z"/><path fill="#f4f3f1" d="M0 0h248v270H0z"/><path fill="#4f5150" d="M8 10h233v203H8z"/>
      </g>
      <g id="polaroid">
        <use xlink:href="#p" transform="rotate(15)" x="175" y="50"/>
        <use xlink:href="#p" transform="rotate(-5)" x="5" y="25"/>
      </g>
    </defs>
  </svg>


  <div id="awaw">
      <img id='beast' src='https://s3.amazonaws.com/bwla/testts.png' />
  </div>

  <div id="photoscroll">
    <div class="slides">

      <div class="slide" id="slide-1">
        <div class="slide__bg"></div>
        <div class="slide__content">
          <div class="slide__image">
            <img id="framed" src='https://s3.amazonaws.com/bwla/home_photos/bwla_un.jpg' />
          </div>
        </div>
      </div>

      <div class="slide" id="slide-2">
        <div class="slide__bg"></div>
        <div class="slide__content">
          <div class="slide__image">
            <img id="framed" src='https://s3.amazonaws.com/bwla/home_photos/bwla_deux.jpg' />
          </div>
        </div>
      </div>

      <div class="slide" id="slide-3">
        <div class="slide__bg"></div>
        <div class="slide__content">
          <div class="slide__image">
            <img id="framed" src='https://s3.amazonaws.com/bwla/home_photos/bwla_troix.jpg' />
          </div>
        </div>
      </div>

      <div class="slide" id="slide-4">
        <div class="slide__bg"></div>
        <div class="slide__content">
          <div class="slide__image">
            <img id="framed" src='https://s3.amazonaws.com/bwla/home_photos/bwla_quatre.jpg' />
          </div>
        </div>
      </div>

      <div class="slide" id="slide-5">
        <div class="slide__bg"></div>
        <div class="slide__content">
          <div class="slide__image">
            <img id="framed" src='https://s3.amazonaws.com/bwla/home_photos/bwla_cinq.jpg' />
          </div>
        </div>
      </div>

      <div class="slide" id="slide-6">
        <div class="slide__bg"></div>
        <div class="slide__content">
          <div class="slide__image">
            <img id="framed" src='https://s3.amazonaws.com/bwla/home_photos/bwla_six.jpg' />
          </div>
        </div>
      </div>

      <div class="slide" id="slide-7">
        <div class="slide__bg"></div>
        <div class="slide__content">
          <div class="slide__image">
            <img id="framed" src='https://s3.amazonaws.com/bwla/home_photos/bwla.sept.jpg' />
          </div>
        </div>
      </div>

    </div>

  </div>
</div>

app/views/page/legal.html.erb
<div style="padding-top: 10%" />

<div class="info_head">
    <h5> TERMS &amp; CONDITIONS </h5>
</div>


<div class="info_head">
    <h6> USING THIS SITE </h6>
</div>
<div class="info">
    <p>Please use a standards-compliant web browser such as Safari 3.0+, Chrome or Firefox 3.0+. Javascript must be enabled to use this site.
    </p>
</div>

<div class="info_head">
    <h6> TERMS OF USE </h6>
</div>
<div class="info">
    <p>By using our website, you agree to the Terms of Use. We may change or update these terms so please check this page regularly. We do not represent or warrant that the information on our web site is accurate, complete, or current. This includes pricing and availability information. We reserve the right to correct any errors or omissions, and to change or update information at any time without prior notice.
    </p>
</div>

<div class="info_head">
    <h6> RETURN POLICY </h6>
</div>
<div class="info">
    <p>Blackwater Atelier will gladly exchange an item for online store credit only. Before sending the item back, please fill out the return form found in your order shipment confirmation within 2 days of receipt of your shipment. Packages sent without first contacting us will not be accepted. Items to be exchanged must be returned in perfect, new condition with all original tags attached. Supreme must receive the returned item within 7 days of return authorization.
    <br /><br />
    For any returned items, you will not be refunded the original cost of shipping, and you are responsible for the cost of the return shipping. Items may not be returned or exchanged in person at any boutique or retail location. Bags, Accessories, Shoes and Sale Items cannot be returned or exchanged. All orders are final and cannot be changed after submission. Blackwater Atelier does not assume responsibility for reimbursement or compensation of returned packages lost in transit without proof of delivery to Blackwater Atelier.
    </p>
</div>

<div class="info_head">
    <h6> COPYRIGHT &amp; TRADEMARKS </h6>
</div>
<div class="info">
    <p>All content of our website including text, graphics, logos, button icons and images are property of BWLA Corp. and are protected by United States and international copyright laws. You may electronically copy and print hard copies of pages from this web site solely for personal, non-commercial purposes related to placing an order or shopping with blackwater-la.com. Any other use of our web site, content, images or information contained therein, including reproduction and internet links, is strictly prohibited without our prior written permission.
    </p>
</div>

<div class="info_head">
    <h6> SECURE PROCESSING </h6>
</div>
<div class="info">
    <p>Blackwater-la.com uses secure processing called SSL Encryption Technology, which is the industry standard, via Stripe checkout integration. SSL(Secure Sockets Layer) is a protocol developed for the transmission of private information over the internet. SSL uses a private key to encrypt your data, including your credit card information, so that it cannot be read while being transferred over the internet.
    </p>
</div>

<div class="info_head">
    <h6> PRIVACY </h6>
</div>
<div class="info">
    <p>Blackwater-la.com respects our customers account information as private and confclassential information and will never share this with any outsclasse afflictions or indivclassuals. Your information is secured and encrypted with the Secure Socket Layer Software. 
    </p>
</div>

<div class="info_head">
    <h6> SHIPPING </h6>
</div>
<div class="info">
    <p>At this time, we are only accepting orders from resclassents that live in the U.S.A..
        <br /><br />
        All orders are shipped via UPS Ground. The shipping rate to the contiguous 48 U.S. states is $5. The shipping rate to Alaska and Hawaii is $20. Please note that UPS does not deliver to APO/FPO addresses or P.O. boxes. 
        <br /><br />
        Please allow 3-5 business days for order processing and verification, and an additional 7-10 business days for delivery. We are not responsible for any lost, stolen, or damaged shipments. All shipments are insured and the buyer assumes all responsibilities of claims made with the shipping carrier.
        <br /><br />
        Please check back with us periodically for any updates regarding our shipping policies.
    </p>
</div>

<div class="info_head">
    <h6> PURCHASE FOR PERSONAL USE ONLY </h6>
</div>
<div class="info">
    <p>You may purchase products only for personal use and not for resale. By placing your order, you certify that you are purchasing products for personal use only and not for resale. We reserve the right to refuse orders for any reason without explanation.
    </p>
</div>

<div class="info_head">
    <h6> SALES TAX </h6>
</div>
<div class="info">
    <p>  
        Sales Tax is charged to those orders shipped within the state of California. The applicable tax rates vary by locality. Shipping is also taxed.
        <br /><br />
        Sales Tax is charged to those orders shipped within the state of New York. All apparel including hats and footwear under $110 are tax exempt. For apparel, hats and footwear over $110 the applicable tax rate is 8.875%. Bags and accessories are not consclassered apparel and are taxable. The applicable tax rate for bags and accessories is 8.875%. Shipping is also taxed.
        <br /><br />
              Sales tax is not charged to orders shipped outsclasse of New York and California.

    </p>
</div>

<div class="info_head">
    <h6> CONTACT INFORMATION </h6>
</div>
<div class="info">
    <p style="text-align:center;">
        <br /><br />
        BLACKWATER ATELIER
        <br />
        23035 PARK PRIVADO
        <br />
        CALABASAS, CA 91302
        <br />
        GENERAL@BLACKWATER-LA.COM
        <br />
        818 983 6036
        <br /> <br />
        <br /> <br />
        <br /> <br />
        <br /> <br />
        <br /> <br />
    </p>
</div>

app/views/page/mailing.html.erb
<h2 id="login">Mailing List<br /> <br /></h2>

    <form id="mailing" action="/">
      
      <h8>
          <input type="text" name="email"><br><br>
      </h8>
      <input type="submit" value="SIGN UP">
    </form>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :subcategory %><br>
    <%= f.text_field :subcategory %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div style="padding-top: 10%" />

<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div style="padding-top: 10%" />

<h1 id="shop_title">
  Fiends &amp; Family Sale
  <div style="margin-bottom: -2px;"></div>
  <span style="opacity: 0.7; font-weight: 400;">
  Printemps-Ete 2016
  </span>

</h1>

<table>
  <tbody>

    <% @products.each do |product| %>
        
        <td>
          <a class="noun" href= "/products/<%= product.id %>">
              <img src="<%= product.image_url %>" id="product_photo" />
          </a>

          <% if user_signed_in? %>
            <%= link_to 'Show', product %>
            <%= link_to 'Edit', edit_product_path(product) %>
            <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %> 
        </td>
        
    <% end %>

  </tbody>
</table>



<% if user_signed_in? %>
  <%= link_to 'New Product', new_product_path %>
<% end %>
<div style="padding-top: 10%" />

app/views/products/new.html.erb
<div style="padding-top: 10%" />

<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

  <div style="padding-top: 10%" />

  
  <div id="right">

    <img src="<%= @product.image_url %>" />

  </div>

  <div id="left">

      <h1 id="product_name">
        <%= @product.title %>
        <br /><br />
      </h1>

        <form id="choosesize" action="/cart/<%= @product.id %>" method="get">

            <span id="price">
              <%= @product.price %>
            </span>

            <span id="purchase">
              <%= submit_tag("ADD TO CART", :class => "fuckmylife") %>
            <span>

          <br /><br />
          <div id="sizebuttons">
            <input id="option" type="radio" name="sizing" value="S">
            <label for="option">S</label>
            
            <input id="option" type="radio" name="sizing" value="M" checked>
            <label for="option">M</label>

            <input id="option" type="radio" name="sizing" value="L">
            <label for="option">L</label>

            <input id="option" type="radio" name="sizing" value="XL">
            <label for="option">XL</label>
          </div>
          <br /><br />
          <br /><br />
          <br /><br />
        </form>

      <p id="product_about">
        <%= @product.description %>
      </p>



      <% if user_signed_in? %>
      <%= link_to 'Edit', edit_product_path(@product) %>
      <p> <%= @product.category %> / <%= @product.subcategory %> </p>
      <% end %>

  </div>
  